insert into COMPANY (id, name) values (1, 'Maria Luísa');
insert into COMPANY (id, name) values (2, 'Layssa');
insert into COMPANY (id, name) values (3, 'Hugo Vinicius');
 call next value for SE_COMPANY;
 call next value for SE_COMPANY;
 call next value for SE_COMPANY;
insert into AUTOR (id, nome) values (1, 'Hugo Vinicius');
insert into AUTOR (id, nome) values (2, 'Layssa Morgara');
insert into AUTOR (id, nome) values (3, 'Maria Luísa');
insert into AUTOR (id, nome) values (4, 'Boneca Sandrinha');
 call next value for SE_AUTOR;
 call next value for SE_AUTOR;
 call next value for SE_AUTOR;
 call next value for SE_AUTOR;